"use client"; // Jika pakai App Router Next 13+

import Head from "next/head";
import {
  Container,
  Heading,
  Spinner,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  Center,
} from "@chakra-ui/react";
import { axiosInstance } from "@/lib/axios";
import { useQuery } from "@tanstack/react-query";

export default function Home() {
  const { data, isLoading } = useQuery({
    queryKey: ["items"],
    queryFn: async () => {
      const itemRes = await axiosInstance.get("/items");
      return itemRes.data;
    },
  });

  const renderItems = () => {
    return data?.map((item) => (
      <Tr key={item.id}>
        <Td>{item.id}</Td>
        <Td>{item.name}</Td>
        <Td>{item.price}</Td>
        <Td>{item.description}</Td>
        <Td>{item.image1}</Td>
      </Tr>
    ));
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Heading my={4}>Home Page</Heading>
          {isLoading ? (
            <Center>
              <Spinner size="xl" />
            </Center>
          ) : (
            <Table>
              <Thead>
                <Tr>
                  <Th>ID</Th>
                  <Th>Name</Th>
                  <Th>Price</Th>
                  <Th>Description</Th>
                  <Th>Image</Th>
                </Tr>
              </Thead>
              <Tbody>{renderItems()}</Tbody>
            </Table>
          )}
        </Container>
      </main>
    </>
  );
}
