import Head from "next/head";
import {
  Container,
  Heading,
  Spinner,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import { useItems } from "@/features/item/useItems";

export default function Home() {
  const { data: items, isLoading } = useItems();

  const renderItems = () => {
    return items.map((item) => {
      return (
        <Tr key={item.id}>
          <Td>{item.id}</Td>
          <Td>{item.name}</Td>
          <Td>{item.price}</Td>
          <Td>{item.description}</Td>
          <Td>{item.image1}</Td>
        </Tr>
      ); //table row
    });
  };

  return (
    <>
      <Head>
        <title>Catalogue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Catalogue Page</Heading>
          <Table>
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>Name</Th>
                <Th>Price</Th>
                <Th>Description</Th>
                <Th>Image</Th>
              </Tr>
            </Thead>
            <Tbody>
              {renderItems()}
              {isLoading ? <Spinner /> : null}
            </Tbody>
          </Table>
        </Container>
      </main>
    </>
  );
}
